In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [3]:
test_array = np.array(["1", "4", 5.0, 8], float)
test_array

array([1., 4., 5., 8.])

In [4]:
type(test_array)

numpy.ndarray

In [5]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
a[0] is b[-1]

True

In [6]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [7]:
# reshape

test_matrix = [[1, 2, 3, 4], [2, 3, 9, 3]]
np.array(test_matrix).shape

(2, 4)

In [8]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 2, 3, 9, 3])

In [9]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [10]:
test_matrix = [[[1, 2, 3, 4], [2, 3, 9, 3]], [[1, 2, 3, 4], [2, 3, 9, 3]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 2, 3, 9, 3, 1, 2, 3, 4, 2, 3, 9, 3])

In [13]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [14]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]], int)
a[:, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [15]:
a[::2, ::3]

array([[ 0,  3],
       [10, 13]])

In [16]:
a = np.empty(shape=(10,), dtype=np.int8)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [17]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [21]:
import pandas as pd

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
df_data = pd.read_csv(data_url, sep='\s+', header=None)

df_data.head() #처음 다섯줄

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [22]:
df_data.columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [23]:
from pandas import Series, DataFrame

dict_data_1 = {"a":1, "b":2, "c":3, "d":4, "e":5}
indexes = ["a", "b", "c", "d", "e", "f", "g", "h"]
series_obj_1 = Series(dict_data_1, index=indexes)
series_obj_1 #index값을 기준으로 series 생성

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
h    NaN
dtype: float64

In [25]:
s1 = Series(np.arange(10))
s1.map(lambda x: x**2).head(5)

0     0
1     1
2     4
3     9
4    16
dtype: int64

In [32]:
df = pd.read_csv("https://raw.githubusercontent.com/rstudio/Intro/master/data/wages.csv")
df.head()

           earn  height     sex   race  ed  age
0  79571.299011   73.89    male  white  16   49
1  96396.988643   66.23  female  white  16   62
2  48710.666947   63.77  female  white  16   33
3  80478.096153   63.22  female  other  16   95
4  82089.345498   63.08  female  white  17   43

In [29]:
print(df.sex.unique())

def change_sex(x):
    return 0 if x == "male" else 1

df.sex.map(change_sex)

['male' 'female']

0       0
1       1
2       1
3       1
4       1
       ..
1374    0
1375    1
1376    1
1377    0
1378    0
Name: sex, Length: 1379, dtype: int64

In [31]:
df["sex_code"] = df.sex.map({"male": 0, "female": 1})
df.head()

           earn  height     sex   race  ed  age  sex_code
0  79571.299011   73.89    male  white  16   49         0
1  96396.988643   66.23  female  white  16   62         1
2  48710.666947   63.77  female  white  16   33         1
3  80478.096153   63.22  female  other  16   95         1
4  82089.345498   63.08  female  white  17   43         1

In [33]:
df = pd.read_csv("https://raw.githubusercontent.com/rstudio/Intro/master/data/wages.csv")
df_info = df[["earn", "height", "age"]]
df_info.head()

           earn  height  age
0  79571.299011   73.89   49
1  96396.988643   66.23   62
2  48710.666947   63.77   33
3  80478.096153   63.22   95
4  82089.345498   63.08   43

In [34]:
f = lambda x : x.max() - x.min()
df_info.apply(f)

earn      318047.708444
height        19.870000
age           73.000000
dtype: float64

In [36]:
def cal(x):
    return Series([x.min(), x.max()], index=["min", "max"])

df_info.apply(cal)

              earn  height  age
min     -98.580489   57.34   22
max  317949.127955   77.21   95

In [37]:
df.sex.value_counts(sort=True)

female    859
male      520
Name: sex, dtype: int64

In [40]:
import dateutil

df_phone = pd.read_csv("phone_data.csv")
df_phone.head()

   index            date  duration  item    month   network network_type
0      0  15/10/14 06:58    34.429  data  2014-11      data         data
1      1  15/10/14 06:58    13.000  call  2014-11  Vodafone       mobile
2      2  15/10/14 14:46    23.000  call  2014-11    Meteor       mobile
3      3  15/10/14 14:48     4.000  call  2014-11     Tesco       mobile
4      4  15/10/14 17:27     4.000  call  2014-11     Tesco       mobile

In [41]:
df_phone['date'] = df_phone["date"].apply(dateutil.parser.parse, dayfirst=True)
df_phone.head()

   index                date  duration  item    month   network network_type
0      0 2014-10-15 06:58:00    34.429  data  2014-11      data         data
1      1 2014-10-15 06:58:00    13.000  call  2014-11  Vodafone       mobile
2      2 2014-10-15 14:46:00    23.000  call  2014-11    Meteor       mobile
3      3 2014-10-15 14:48:00     4.000  call  2014-11     Tesco       mobile
4      4 2014-10-15 17:27:00     4.000  call  2014-11     Tesco       mobile

In [45]:
df_phone.dtypes

index                    int64
date            datetime64[ns]
duration               float64
item                    object
month                   object
network                 object
network_type            object
dtype: object

In [47]:
df_phone.groupby("month")["duration"].sum()

month
2014-11    26639.441
2014-12    14641.870
2015-01    18223.299
2015-02    15522.299
2015-03    22750.441
Name: duration, dtype: float64

In [48]:
df_phone[df_phone['item'] == 'call'].groupby('network')['duration'].sum()

network
Meteor        7200.0
Tesco        13828.0
Three        36464.0
Vodafone     14621.0
landline     18433.0
voicemail     1775.0
Name: duration, dtype: float64

In [50]:
df_phone.groupby(['month', 'item'])['date'].count()

month    item
2014-11  call    107
         data     29
         sms      94
2014-12  call     79
         data     30
         sms      48
2015-01  call     88
         data     31
         sms      86
2015-02  call     67
         data     31
         sms      39
2015-03  call     47
         data     29
         sms      25
Name: date, dtype: int64

In [51]:
df_phone.groupby(['month', 'item'])['date'].count().unstack()

item     call  data  sms
month
2014-11   107    29   94
2014-12    79    30   48
2015-01    88    31   86
2015-02    67    31   39
2015-03    47    29   25

In [52]:
df_phone.groupby("month", as_index=False).agg({"duration": "sum"})

     month   duration
0  2014-11  26639.441
1  2014-12  14641.870
2  2015-01  18223.299
3  2015-02  15522.299
4  2015-03  22750.441

In [53]:
df_phone.groupby(['month', 'item']).agg({"duration": sum, "network_type": "count", "date": "first"})

               duration  network_type                date
month   item
2014-11 call  25547.000           107 2014-10-15 06:58:00
        data    998.441            29 2014-10-15 06:58:00
        sms      94.000            94 2014-10-16 22:18:00
2014-12 call  13561.000            79 2014-11-14 17:24:00
        data   1032.870            30 2014-11-13 06:58:00
        sms      48.000            48 2014-11-14 17:28:00
2015-01 call  17070.000            88 2014-12-15 20:03:00
        data   1067.299            31 2014-12-13 06:58:00
        sms      86.000            86 2014-12-15 19:56:00
2015-02 call  14416.000            67 2015-01-15 10:36:00
        data   1067.299            31 2015-01-13 06:58:00
        sms      39.000            39 2015-01-15 12:23:00
2015-03 call  21727.000            47 2015-02-12 20:15:00
        data    998.441            29 2015-02-13 06:58:00
        sms      25.000            25 2015-02-19 18:46:00

In [54]:
df_phone.groupby(['month', 'item']).agg({"duration": [min, max, sum], "network_type": "count", "date": [min, 'first', 'nunique']})

             duration                       network_type                date  \
                  min        max        sum        count                 min
month   item
2014-11 call    1.000   1940.000  25547.000          107 2014-10-15 06:58:00
        data   34.429     34.429    998.441           29 2014-10-15 06:58:00
        sms     1.000      1.000     94.000           94 2014-10-16 22:18:00
2014-12 call    2.000   2120.000  13561.000           79 2014-11-14 17:24:00
        data   34.429     34.429   1032.870           30 2014-11-13 06:58:00
        sms     1.000      1.000     48.000           48 2014-11-14 17:28:00
2015-01 call    2.000   1859.000  17070.000           88 2014-12-15 20:03:00
        data   34.429     34.429   1067.299           31 2014-12-13 06:58:00
        sms     1.000      1.000     86.000           86 2014-12-15 19:56:00
2015-02 call    1.000   1863.000  14416.000           67 2015-01-15 10:36:00
        data   34.429     34.429   1067.299           31 2015-01-13 06:58:00
        sms     1.000      1.000     39.000           39 2015-01-15 12:23:00
2015-03 call    2.000  10528.000  21727.000           47 2015-02-12 20:15:00
        data   34.429     34.429    998.441           29 2015-02-13 06:58:00
        sms     1.000      1.000     25.000           25 2015-02-19 18:46:00


                           first nunique
month   item
2014-11 call 2014-10-15 06:58:00     104
        data 2014-10-15 06:58:00      29
        sms  2014-10-16 22:18:00      79
2014-12 call 2014-11-14 17:24:00      76
        data 2014-11-13 06:58:00      30
        sms  2014-11-14 17:28:00      41
2015-01 call 2014-12-15 20:03:00      84
        data 2014-12-13 06:58:00      31
        sms  2014-12-15 19:56:00      58
2015-02 call 2015-01-15 10:36:00      67
        data 2015-01-13 06:58:00      31
        sms  2015-01-15 12:23:00      27
2015-03 call 2015-02-12 20:15:00      47
        data 2015-02-13 06:58:00      29
        sms  2015-02-19 18:46:00      17

In [56]:
df_phone_2 = pd.read_csv("phone_data.csv")
df_phone_2['date'] = df_phone_2["date"].apply(dateutil.parser.parse, dayfirst=True)
df_phone_2.head()

   index                date  duration  item    month   network network_type
0      0 2014-10-15 06:58:00    34.429  data  2014-11      data         data
1      1 2014-10-15 06:58:00    13.000  call  2014-11  Vodafone       mobile
2      2 2014-10-15 14:46:00    23.000  call  2014-11    Meteor       mobile
3      3 2014-10-15 14:48:00     4.000  call  2014-11     Tesco       mobile
4      4 2014-10-15 17:27:00     4.000  call  2014-11     Tesco       mobile

In [57]:
df_phone_2.pivot_table(['duration'], index=[df_phone_2.month, df_phone_2.item], columns=df_phone_2.network, aggfunc="sum", fill_value=0)

             duration                                                   \
network        Meteor Tesco  Three Vodafone      data landline special
month   item
2014-11 call     1521  4045  12458     4316     0.000     2906       0
        data        0     0      0        0   998.441        0       0
        sms        10     3     25       55     0.000        0       1
2014-12 call     2010  1819   6316     1302     0.000     1424       0
        data        0     0      0        0  1032.870        0       0
        sms        12     1     13       18     0.000        0       0
2015-01 call     2207  2904   6445     3626     0.000     1603       0
        data        0     0      0        0  1067.299        0       0
        sms        10     3     33       40     0.000        0       0
2015-02 call     1188  4087   6279     1864     0.000      730       0
        data        0     0      0        0  1067.299        0       0
        sms         1     2     11       23     0.000        0       2
2015-03 call      274   973   4966     3513     0.000    11770       0
        data        0     0      0        0   998.441        0       0
        sms         0     4      5       13     0.000        0       0


network      voicemail world
month   item
2014-11 call       301     0
        data         0     0
        sms          0     0
2014-12 call       690     0
        data         0     0
        sms          0     4
2015-01 call       285     0
        data         0     0
        sms          0     0
2015-02 call       268     0
        data         0     0
        sms          0     0
2015-03 call       231     0
        data         0     0
        sms          0     3

In [58]:
df_movie = pd.read_csv("https://raw.githubusercontent.com/TeamLab/machine_learning_from_scratch_with_python/master/code/ch5/data/movie_rating.csv")
df_movie.head()

          critic               title  rating
0  Jack Matthews   Lady in the Water     3.0
1  Jack Matthews   Snakes on a Plane     4.0
2  Jack Matthews   You Me and Dupree     3.5
3  Jack Matthews    Superman Returns     5.0
4  Jack Matthews  The Night Listener     3.0

In [59]:
pd.crosstab(index=df_movie.critic, columns=df_movie.title, values=df_movie.rating, aggfunc='first').fillna(0)

title,Just My Luck,Lady in the Water,Snakes on a Plane,Superman Returns,The Night Listener,You Me and Dupree
critic,,,,,,
Claudia Puig,3.0,0.0,3.5,4.0,4.5,2.5
Gene Seymour,1.5,3.0,3.5,5.0,3.0,3.5
Jack Matthews,0.0,3.0,4.0,5.0,3.0,3.5
Lisa Rose,3.0,2.5,3.5,3.5,3.0,2.5
Mick LaSalle,2.0,3.0,4.0,3.0,3.0,2.0
Toby,0.0,0.0,4.5,4.0,0.0,1.0

In [66]:
def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

#np.lingalg.norm -> l2 norm 가능

def angle(x, y):
    v = np.inner(x, y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

22 55

In [68]:
X = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])
Y = np.array([[0, 1], [1, -1], [-2, 1]])
X @ Y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

In [69]:
X = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])
Y = np.array([[0, 1, -1], [1, -1, 0]])
np.inner(X, Y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

In [70]:
X = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])
np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [71]:
X @ np.linalg.inv(X)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

In [72]:
Y = np.array([[0, 1], [1, -1], [-2, 1]])
np.linalg.pinv(Y)

array([[ 5.00000000e-01,  1.11022302e-16, -5.00000000e-01],
       [ 8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [73]:
np.linalg.pinv(Y) @ Y

array([[ 1.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  1.00000000e+00]])

In [74]:
Y @ np.linalg.pinv(Y) # 항등행렬 안나옴!

array([[ 0.83333333, -0.33333333, -0.16666667],
       [-0.33333333,  0.33333333, -0.33333333],
       [-0.16666667, -0.33333333,  0.83333333]])

In [76]:
Z = np.array([[0, 1, -1], [1, -1, 0]])
Z @ np.linalg.pinv(Z)

array([[ 1.00000000e+00, -3.88578059e-16],
       [ 2.22044605e-16,  1.00000000e+00]])

In [77]:
import sympy as sym
from sympy.abc import x

sym.diff(sym.poly(x**2 + 2*x + 3), x)

Poly(2*x + 2, x, domain='ZZ')

# Input : gradient(미분을 계산하는 함수), init(시작점), lr(학습률), eps(알고리즘 종료조건)
# Output : var

var = init
grad = gradient(var)
while(abs(grad) > eps):
    var = var - lr * grad
    grad = gradient(var)

In [78]:
# f(x)=x**2 + 2*x + 3 일때 경사하강법으로 최소점을 찾는 코드

def func(val):
    fun = sym.poly(x**2 + 2*x + 3)
    return fun.subs(x, val), fun

def func_gradient(fun, val):
    _, function = fun(val)
    diff = sym.diff(function, x)
    return diff.subs(x, val), diff

def gradient_descent(fun, init_point, lr_rate=1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, init_point)
    while np.abs(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
    print("함수: {}, 연산횟수: {}, 최소점: ({}, {})".format(fun(val)[1], cnt, val, fun(val)[0]))

gradient_descent(fun=func, init_point=np.random.uniform(-2, 2))

함수: Poly(x**2 + 2*x + 3, x, domain='ZZ'), 연산횟수: 577, 최소점: (-0.999995012551946, 2.00000000002487)

In [80]:
import sympy as sym
from sympy.abc import x, y

sym.diff(sym.poly(x**2 + 2*x*y + 3) + sym.cos(x + 2*y), x)

2*x + 2*y - sin(x + 2*y)

# Input : gradient(그래디언트 벡터를 계산하는 함수), init(시작점), lr(학습률), eps(알고리즘 종료조건)
# Output : var

var = init
grad = gradient(var)
while(norm(grad) > eps):
# abs대신 노름 norm 사용
    var = var - lr * grad
    grad = gradient(var)

In [83]:
# f(x, y)=(x**2 + 2*x*y + 3) + cos(x + 2*y) 일때 경사하강법으로 최소점을 찾는 코드
def eval_(fun, val):
    val_x, val_y = val
    fun_eval = fun.subs(x, val_x).subs(y, val_y) #.subs(a, b):a에 b를 넣겠다! 
    return fun_eval

# 수식을 정의
def func_multi(val):
    x_, y_ = val
    func = sym.poly(x**2 + 2*y**2)
    return eval_(func, [x_, y_]), func

# 수식에 대해 x와 y로 미분함
def func_gradient(fun, val):
    x_, y_ = val
    _, function = fun(val)
    diff_x = sym.diff(function, x)
    diff_y = sym.diff(function, y)
    grad_vec = np.array([eval_(diff_x, [x_, y_]), eval_(diff_y, [x_, y_])], dtype=float)
    return grad_vec, [diff_x, diff_y]

# 기울기 방향으로 점을 업데이트
def gradient_descent(fun, init_point, lr_rate=1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, val) # 두번째 반환값은 무시
    while np.linalg.norm(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
    print("함수: {}, 연산횟수: {}, 최소점: ({}, {})".format(fun(val)[1], cnt, val, fun(val)[0]))

pt = [np.random.uniform(-2, 2), np.random.uniform(-2, 2)]
gradient_descent(fun=func_multi, init_point=pt)

함수: Poly(x**2 + 2*y**2, x, y, domain='ZZ'), 연산횟수: 639, 최소점: ([-4.92093276e-06  1.75372665e-12], 2.42155791832000E-11)

In [84]:
def softmax(vec):
    denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))
    numerator = np.sum(denumerator, axis=-1, keepdims=True)
    val = denumerator / numerator
    return val

vec = np.array([[1, 2, 0], [-1, 0, 1], [-10, 0, 10]])
softmax(vec)

array([[2.44728471e-01, 6.65240956e-01, 9.00305732e-02],
       [9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [2.06106005e-09, 4.53978686e-05, 9.99954600e-01]])

In [85]:
def one_hot(val, dim):
    return [np.eye(dim)[_] for _ in val]

def one_hot_encoding(vec):
    vec_dim = vec.shape[1]
    vec_argmax = np.argmax(vec, axis=-1)
    return one_hot(vec_argmax, vec_dim)

def softmax(vec):
    denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))
    numerator = np.sum(denumerator, axis=-1, keepdims=True)
    val = denumerator / numerator
    return val

vec = np.array([[1, 2, 0], [-1, 0, 1], [-10, 0, 10]])
print(one_hot_encoding(vec))
print(one_hot_encoding(softmax(vec)))

[array([0., 1., 0.]), array([0., 0., 1.]), array([0., 0., 1.])]
[array([0., 1., 0.]), array([0., 0., 1.]), array([0., 0., 1.])]

In [86]:
# 몬테카를로 법칙으로 적분 계산하기

def mc_int(fun, low, high, sample_size=100, repeat=10):
    int_len = np.abs(high - low)
    stat = []
    for _ in range(repeat):
        x = np.random.uniform(low=low, high=high, size=sample_size)
        fun_x = fun(x)
        int_val = int_len * np.mean(fun_x)
        stat.append(int_val)
    return np.mean(stat), np.std(stat)

def f_x(x):
    return np.exp(-x**2)

print(mc_int(f_x, low=-1, high=1, sample_size=1000, repeat=100))

(1.4926732675088998, 0.010780851509393376)